markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true              # require by this theme
    lineNumbersInTable: false  # require by this theme
    noClasses: false           # require by this theme
    noHl: false
    style: dracula    # hugo gen chromastyles --style=dracula > assets/main/scss/_highlight.scss
    tabWidth: 4
