name: Może Bałtyk
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: 'Infrastructure Engineer, Ansibler, Future Gopher.'
company: Home  # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a> # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://hbs.razonyang.com/v1/en/docs/widgets/social-links/.
social:
  #email: @gmail.com
  github: MozeBaltyk/mozebaltyk.github.io
  #twitter: razonyang
  #patreon: razonyang
  #paypal: razonyang
  rss: "" # Remove RSS
